
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from home import homePage
from pathlib import Path

 #from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title('AItingMusic')
window.geometry("1154x681")
window.configure(bg = "#FFFFFF")



canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 681,
    width = 1154,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
homePage()
canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
     file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    761.5,
    48.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D47B7B",
    highlightthickness=0
)
entry_1.place(
    x=549.0,
    y=17.0,
    width=425.0,
    height=60.0
)





#左侧歌曲名称显示区
canvas.create_rectangle(
    0.0,
    103.0,
    471.0,
    681.0,
    fill="#FAB3B3",
    outline="red")



#Logo显示区
canvas.create_text(
    125.0,
    12.0,
    anchor="nw",
    text="AItingMusic\n",
    fill="#FF0000",
    font=("SairaExtraCondensed Regular", 48 * -1)
)


"""按钮"""
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))

button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: creatPage(),
    relief="flat"
)

button_1.place(
    x=1022.0,
    y=22.0,
    width=88.0,
    height=53.0
)

canvas.create_text(
    1044.0,
    28.0,
    anchor="nw",
    text="s",
    fill="#FFFFFF",
    font=("SairaExtraCondensed Regular", 24 * -1)
)
 #我试图将参数传递给处理函数后令其将结果返回，然后呈现在GUI上


#右侧歌词文本框
def creatPage():
    musciname = entry_1.get()
    homePage().searchSingle(musciname)
    f = open('Lyrics.csv', 'r', encoding='utf-8')
    lyric = f.readlines()
    print('右侧文本框创建成功')
    canvas.create_rectangle(
        471.0,
        103.0,
        1154.0,
        681.0,
        fill="#E2C3C3",
        outline="green")

    """文本展示区"""
    canvas.create_text(
        513.0,
        110.0,
        anchor="nw",
        text=lyric,  # 显示歌词。
        fill="#000000",
        font=("SairaExtraCondensed Regular", 18 * -1)
    )


window.resizable(False, False)
window.mainloop()
